<?php

// receipt

$pageTitle = 'Receipt';
require_once __DIR__ . '/layout/header.php';

$txId = (int) ($_GET['id'] ?? 0);
if (!$txId) {
    echo '<p class="text-sm text-red-600">No transaction specified.</p>';
    require_once __DIR__ . '/layout/footer.php';
    exit;
}

$tx = \Models\Transaction::findById($txId);

// check ownership
if (!$tx || $tx['internet_id'] !== $user['internet_id']) {
    echo '<p class="text-sm text-red-600">Transaction not found.</p>';
    require_once __DIR__ . '/layout/footer.php';
    exit;
}

$siteName = defined('APP_NAME') ? APP_NAME : 'Banking';
?>

<div class="max-w-2xl mx-auto">
    <div id="receipt" class="bg-white dark:bg-white/5 rounded-3xl shadow-sm p-8">
        <!-- header -->
        <div class="text-center mb-8 pb-6 border-b border-gray-200 dark:border-white/10">
            <h1 class="text-xl font-medium tracking-tighter text-gray-900 dark:text-white"><?= htmlspecialchars($siteName) ?></h1>
            <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">Transaction Receipt</p>
        </div>

        <!-- transaction details -->
        <dl class="space-y-4 text-sm">
            <?php
            $details = [
                'Reference ID' => htmlspecialchars($tx['reference_id']),
                'Date' => \Helpers\Format::dateTime($tx['created_at']),
                'Type' => ucfirst($tx['type']),
                'Direction' => ucfirst($tx['trans_type']),
                'Amount' => \Helpers\Format::currency($tx['amount'], $tx['currency'] ?? $currency),
            ];
            if ((float) $tx['fee'] > 0) {
                $details['Fee'] = \Helpers\Format::currency($tx['fee'], $tx['currency'] ?? $currency);
            }
            $details['Status'] = ucfirst($tx['status']);
            if ($tx['description']) $details['Description'] = htmlspecialchars($tx['description']);
            if ($tx['payment_account']) $details['Payment Account'] = ucfirst(str_replace('_', ' ', $tx['payment_account']));
            if ($tx['recipient_name']) $details['Recipient'] = htmlspecialchars($tx['recipient_name']);
            if ($tx['recipient_account']) $details['Recipient Account'] = htmlspecialchars($tx['recipient_account']);
            if ($tx['recipient_bank']) $details['Recipient Bank'] = htmlspecialchars($tx['recipient_bank']);
            if ($tx['recipient_country']) $details['Country'] = htmlspecialchars($tx['recipient_country']);
            if ($tx['swift_code']) $details['SWIFT Code'] = htmlspecialchars($tx['swift_code']);
            if ($tx['routing_number']) $details['Routing Number'] = htmlspecialchars($tx['routing_number']);

            foreach ($details as $label => $value): ?>
                <div class="flex justify-between">
                    <dt class="font-medium text-gray-500 dark:text-gray-400"><?= $label ?></dt>
                    <dd class="text-gray-900 dark:text-white text-right"><?= $value ?></dd>
                </div>
            <?php endforeach; ?>
        </dl>

        <!-- footer -->
        <div class="mt-8 pt-6 border-t border-gray-200 dark:border-white/10 text-center">
            <p class="text-xs text-gray-400 dark:text-gray-500">This is an electronic receipt generated by <?= htmlspecialchars($siteName) ?>.</p>
            <p class="text-xs text-gray-400 dark:text-gray-500 mt-1">Generated on <?= date('M d, Y h:i A') ?></p>
        </div>
    </div>

    <!-- actions -->
    <div class="mt-6 flex justify-center gap-3">
        <button onclick="window.print()" class="px-5 py-2 rounded-full bg-[#1e0e62] text-white text-sm font-medium">Print Receipt</button>
        <a href="<?= $baseUrl ?>/accounts/history.php" class="px-5 py-2 rounded-full border border-gray-200 dark:border-white/10 text-sm font-medium text-gray-700 dark:text-gray-300">Back to History</a>
    </div>
</div>

<?php
$pageScripts = '<style>@media print { body > div > header, aside, #sidebar-overlay, .mt-6 { display: none; } body > div { margin: 0; } }</style>';
require_once __DIR__ . '/layout/footer.php';
?>
